version: 0.2
phases:
  install:
    commands:
    - echo "Adding HashiCorp's GPG key and repo for Terraform..."
    - wget -O - https://apt.releases.hashicorp.com/gpg |  gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    - apt update &&  apt -y install terraform &&  apt install -y software-properties-common &&  add-apt-repository --yes --update ppa:ansible/ansible && apt install -y ansible
    - terraform version
  pre_build:
    commands:
    # Initialisation of terraform 
    - echo "Terraform init in the process"
    - cd "Terraform-project/"
    - terraform init
  build:
    commands:
    - echo "Apply Terraform script in the process"
    - terraform apply -auto-approve
  post_build:
    commands:
    - cd ../automation_ansible
    - echo "switching to configuration of the instances"

    - sudo chmod +x retrieve-ip.sh
    - ./retrieve-ip.sh

    - echo "[*] Installing Docker Ansible collection"
    - ansible-galaxy collection install community.docker
    - cat ./private_key.pem
    - sudo chmod 600 ./private_key.pem
    - ansible-playbook -vvv ConfigurationServer.yaml -i instance-asg
