
version: 0.2
phases:
  install:
    commands:
      - echo "Adding HashiCorp's GPG key and repo for Terraform..."
      - wget -O - https://apt.releases.hashicorp.com/gpg |  gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - apt update &&  apt -y install terraform
      - terraform version
  pre_build:
    commands:
    # Initialisation of terraform 
      - echo "Terraform init in the process"
      - terraform init
  build:
    commands:
      - echo "Terraform plan in the process"
      - terraform plan
      - echo "Apply Terraform script in the process"
      - terraform apply -auto-approve
