version: 0.2
phases:
  install:
    commands:
    - sudo apt update
    - sudo apt install -y software-properties-common && sudo add-apt-repository --yes --update ppa:ansible/ansible && sudo apt install -y ansible

  build:
    commands:
    - cd automation_ansible
    - echo "switching to configuration of the instances"
    - sudo chmod +x retrieve-ip.sh
    - ./retrieve-ip.sh
    - echo "[*] Installing Docker Ansible collection"
    - ansible-galaxy collection install community.docker
    - echo "$ANSIBLE_KEY"| base64 -d > private_key.pem
    - cat ./private_key.pem
    - chmod 600 private_key.pem
    - ansible-playbook -vvv ConfigurationServer.yaml -i instance-asg
